# Generated by Django 6.0 on 2025-12-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('analyst', 'Analyst'), ('admin', 'Admin')], default='operator', max_length=20),
        ),
    ]
