# Generated by Django 6.0 on 2025-12-06 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vessel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='voyage',
            options={'ordering': ['departure_date']},
        ),
        migrations.AlterField(
            model_name='event',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.voyage'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='current_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vessels', to='api.port'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='api.vessel'),
        ),
    ]
