# Generated by Django 6.0 on 2025-12-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vessel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='voyage',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('operator', 'Operator'), ('analyst', 'Analyst'), ('admin', 'Admin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='current_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.port'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='api.port'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='api.port'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vessel'),
        ),
    ]
