# Generated by Django 6.0 on 2025-12-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_port_options_alter_vessel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('analyst', 'Analyst'), ('admin', 'Admin')], default='operator', max_length=20),
        ),
    ]
