# Generated by Django 6.0 on 2025-12-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ANALYST', 'Analyst'), ('OPERATOR', 'Operator')], default='OPERATOR', max_length=20),
        ),
    ]
