# Generated by Django 6.0 on 2026-01-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Operator', 'Operator'), ('Analyst', 'Analyst'), ('Admin', 'Admin')], default='Operator', max_length=20),
        ),
    ]
