# Generated by Django 4.2.7 on 2025-12-25 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_position_updates', models.BooleanField(default=False)),
                ('email_status_changes', models.BooleanField(default=True)),
                ('email_port_activities', models.BooleanField(default=True)),
                ('email_emergencies', models.BooleanField(default=True)),
                ('email_weather_warnings', models.BooleanField(default=True)),
                ('app_position_updates', models.BooleanField(default=True)),
                ('app_status_changes', models.BooleanField(default=True)),
                ('app_port_activities', models.BooleanField(default=True)),
                ('app_emergencies', models.BooleanField(default=True)),
                ('app_weather_warnings', models.BooleanField(default=True)),
                ('position_update_frequency', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('position_update', 'Position Update'), ('status_change', 'Status Change'), ('port_arrival', 'Port Arrival'), ('port_departure', 'Port Departure'), ('speed_change', 'Speed Change'), ('course_change', 'Course Change'), ('emergency', 'Emergency Alert'), ('maintenance', 'Maintenance Alert'), ('weather_warning', 'Weather Warning'), ('subscription', 'Subscription Update')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['vessel', 'notification_type'], name='notificatio_vessel__b24f69_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
