# Generated by Django 4.2.7 on 2025-12-24 12:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "imo",
                    models.CharField(
                        help_text="International Maritime Organization number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "mmsi",
                    models.CharField(
                        help_text="Maritime Mobile Service Identity",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "vessel_type",
                    models.CharField(
                        choices=[
                            ("cargo", "Cargo Ship"),
                            ("tanker", "Tanker"),
                            ("container", "Container Ship"),
                            ("passenger", "Passenger Ship"),
                            ("fishing", "Fishing Vessel"),
                            ("bulk_carrier", "Bulk Carrier"),
                            ("ro_ro", "RoRo Ship"),
                            ("offshore", "Offshore Vessel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cargo_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("general", "General Cargo"),
                            ("crude_oil", "Crude Oil"),
                            ("lng", "LNG"),
                            ("containers", "Containers"),
                            ("bulk", "Bulk Cargo"),
                            ("chemicals", "Chemicals"),
                            ("passengers", "Passengers"),
                        ],
                        max_length=20,
                    ),
                ),
                ("flag", models.CharField(max_length=50)),
                (
                    "capacity",
                    models.PositiveIntegerField(help_text="Capacity in tons or TEU"),
                ),
                ("length", models.FloatField(help_text="Length in meters")),
                ("width", models.FloatField(help_text="Width in meters")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ports.port",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Voyage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_date", models.DateTimeField()),
                ("estimated_arrival", models.DateTimeField()),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("delayed", "Delayed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        blank=True, help_text="Distance in nautical miles", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voyages_to",
                        to="ports.port",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voyages_from",
                        to="ports.port",
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voyages",
                        to="vessels.vessel",
                    ),
                ),
            ],
            options={
                "ordering": ["-departure_date"],
            },
        ),
        migrations.CreateModel(
            name="VesselPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
                ("speed", models.FloatField(help_text="Speed in knots")),
                ("course", models.FloatField(help_text="Course in degrees")),
                (
                    "heading",
                    models.FloatField(
                        blank=True, help_text="Heading in degrees", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(default="Under way using engine", max_length=50),
                ),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="vessels.vessel",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
            },
        ),
    ]
