# Generated by Django 4.2.7 on 2025-12-25 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('vessel_type', models.CharField(choices=[('cargo', 'Cargo Ship'), ('tanker', 'Tanker'), ('container', 'Container Ship'), ('passenger', 'Passenger Ship'), ('fishing', 'Fishing Vessel'), ('military', 'Military Vessel'), ('other', 'Other')], max_length=20)),
                ('flag', models.CharField(max_length=50)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('gross_tonnage', models.IntegerField(blank=True, null=True)),
                ('built_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VesselPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VesselSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vessels.vessel')),
            ],
            options={
                'unique_together': {('user', 'vessel')},
            },
        ),
    ]
