# Generated by Django 4.2.7 on 2026-01-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='call_sign',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vessel',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vessel',
            name='imo_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='flag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
