# Generated by Django 6.0 on 2025-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_vessel_latitude_vessel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='cargo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='flag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='imo_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='mmsi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='route',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='vessel_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
