# Generated by Django 4.2.7 on 2026-01-20 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vessels", "0003_voyagereplay_voyageposition_complianceviolation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="voyageposition",
            new_name="vessels_voy_voyage__c13d41_idx",
            old_name="vessels_voy_voyage__idx",
        ),
    ]
