# Generated by Django 6.0 on 2025-12-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0003_vessel_cargo_vessel_flag_vessel_imo_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, help_text='Speed over ground (knots)', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Course over ground (degrees)', null=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vessels.vessel')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['vessel', 'timestamp'], name='vessels_ves_vessel__3556bb_idx')],
            },
        ),
    ]
