# Generated by Django 4.2.7 on 2026-01-06 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vessels', '0003_voyage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeDataSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('global', 'Global Coverage'), ('region', 'Regional Coverage'), ('vessel_specific', 'Specific Vessels')], default='global', max_length=20)),
                ('notification_types', models.JSONField(default=list)),
                ('min_latitude', models.FloatField(blank=True, null=True)),
                ('max_latitude', models.FloatField(blank=True, null=True)),
                ('min_longitude', models.FloatField(blank=True, null=True)),
                ('max_longitude', models.FloatField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('update_frequency', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vessels', models.ManyToManyField(blank=True, to='vessels.vessel')),
            ],
        ),
    ]
