# Generated by Django 4.2.7 on 2026-01-13 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vessels', '0004_realtimedatasubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVesselSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(max_length=20)),
                ('vessel_name', models.CharField(blank=True, max_length=100)),
                ('position_updates', models.BooleanField(default=True)),
                ('destination_alerts', models.BooleanField(default=True)),
                ('status_changes', models.BooleanField(default=True)),
                ('update_frequency', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_vessel_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mmsi')},
            },
        ),
    ]
