# Generated by Django 6.0 on 2025-12-17 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0004_vesselposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_enter_exit_port', models.BooleanField(default=False)),
                ('alert_speed_threshold', models.BooleanField(default=False)),
                ('alert_status_change', models.BooleanField(default=False)),
                ('speed_threshold', models.FloatField(blank=True, help_text='Knots for speed alerts', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to='vessels.vessel')),
            ],
            options={
                'unique_together': {('user', 'vessel')},
            },
        ),
        migrations.CreateModel(
            name='VesselAlertTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('enter_port', 'Enter Port'), ('exit_port', 'Exit Port'), ('speed_threshold', 'Speed Threshold Exceeded'), ('status_change', 'Status Change')], max_length=32)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='vessels.vesselalertsubscription')),
            ],
            options={
                'ordering': ('-triggered_at',),
            },
        ),
    ]
