# Generated by Django 4.2.7 on 2026-01-20 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "vessels",
            "0004_rename_vessels_voy_voyage__idx_vessels_voy_voyage__c13d41_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voyageposition",
            name="voyage",
        ),
        migrations.RemoveField(
            model_name="voyagereplay",
            name="destination_port",
        ),
        migrations.RemoveField(
            model_name="voyagereplay",
            name="origin_port",
        ),
        migrations.RemoveField(
            model_name="voyagereplay",
            name="vessel",
        ),
        migrations.DeleteModel(
            name="ComplianceViolation",
        ),
        migrations.DeleteModel(
            name="VoyagePosition",
        ),
        migrations.DeleteModel(
            name="VoyageReplay",
        ),
    ]
