# Generated by Django 6.0 on 2025-12-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0005_vesselalertsubscription_vesselalerttrigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='imo_number',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='route',
        ),
        migrations.AddField(
            model_name='vessel',
            name='imo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vesselposition',
            name='course',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='mmsi',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vesselposition',
            name='heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vesselposition',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vesselposition',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['mmsi'], name='vessels_ves_mmsi_d9a636_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['imo'], name='vessels_ves_imo_951588_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselposition',
            index=models.Index(fields=['timestamp'], name='vessels_ves_timesta_6b6658_idx'),
        ),
    ]
