# Generated by Django 6.0 on 2025-12-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0006_remove_vessel_cargo_remove_vessel_imo_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vesselposition',
            unique_together={('vessel', 'timestamp')},
        ),
    ]
