# Generated by Django 6.0 on 2025-12-18 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0007_alter_vesselposition_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('speed', 'Speed'), ('port', 'Port'), ('status', 'Status')], max_length=16)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_alerts', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vessels.vessel')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='vessels_ves_user_id_378be6_idx'), models.Index(fields=['vessel', 'created_at'], name='vessels_ves_vessel__a2f5ba_idx'), models.Index(fields=['alert_type', 'created_at'], name='vessels_ves_alert_t_31a844_idx')],
            },
        ),
        migrations.CreateModel(
            name='VesselSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_types', models.JSONField(default=list, help_text='List of alert types: speed, port, status')),
                ('speed_threshold', models.FloatField(blank=True, help_text="Speed threshold in knots for 'speed' alerts.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_alert_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='vessels.vessel')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'vessel'], name='vessels_ves_user_id_6d6a34_idx'), models.Index(fields=['vessel', 'is_active'], name='vessels_ves_vessel__189a4a_idx')],
                'unique_together': {('user', 'vessel')},
            },
        ),
    ]
