# Generated by Django 5.0.14 on 2025-12-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='last_course',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
