# Generated by Django 5.2.9 on 2025-12-08 07:36

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('analyst', 'Analyst'), ('admin', 'Admin')], db_index=True, default='operator', max_length=20)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'core_user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('incident', 'Incident'), ('other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('congestion_score', models.FloatField(default=0.0)),
                ('avg_wait_time', models.FloatField(default=0.0)),
                ('arrivals', models.IntegerField(default=0)),
                ('departures', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_port',
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=100)),
                ('cargo_type', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=255)),
                ('last_position_lat', models.FloatField(blank=True, null=True)),
                ('last_position_lon', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_vessel',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('alert', 'Alert'), ('update', 'Update')], db_column='type', default='info', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.event')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(db_column='vessel_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.vessel')),
            ],
            options={
                'db_table': 'core_notification',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='vessel',
            field=models.ForeignKey(db_column='vessel_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.vessel'),
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('port_from', models.ForeignKey(db_column='port_from', on_delete=django.db.models.deletion.CASCADE, related_name='voyages_from', to='core.port')),
                ('port_to', models.ForeignKey(db_column='port_to', on_delete=django.db.models.deletion.CASCADE, related_name='voyages_to', to='core.port')),
                ('vessel', models.ForeignKey(db_column='vessel_id', on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='core.vessel')),
            ],
            options={
                'db_table': 'core_voyage',
                'ordering': ['-departure_time'],
            },
        ),
    ]
