# Generated by Django 5.2.9 on 2025-12-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('marinetraffic', 'MarineTraffic'), ('aishub', 'AIS Hub')], max_length=20, unique=True)),
                ('api_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_api_key',
            },
        ),
        migrations.CreateModel(
            name='VesselPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(choices=[('marinetraffic', 'MarineTraffic'), ('aishub', 'AIS Hub')], default='marinetraffic', max_length=20)),
                ('vessel', models.ForeignKey(db_column='vessel_id', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.vessel')),
            ],
            options={
                'db_table': 'core_vessel_position',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vessel', '-timestamp'], name='core_vessel_vessel__6822c9_idx'), models.Index(fields=['timestamp'], name='core_vessel_timesta_d414aa_idx')],
            },
        ),
    ]
