# Generated by Django 5.2.9 on 2025-12-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterModelTable(
            name='user',
            table='core_user',
        ),
    ]
