# Generated by Django 5.2.9 on 2025-12-18 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apikey_vesselposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VesselSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('position_update', 'Position Update'), ('departure', 'Departure'), ('arrival', 'Arrival'), ('speed_change', 'Speed Change'), ('course_change', 'Course Change'), ('all', 'All Events')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='vessel_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(db_column='vessel_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.vessel')),
            ],
            options={
                'db_table': 'core_vessel_subscription',
            },
        ),
        migrations.CreateModel(
            name='VesselAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('position_update', 'Position Update'), ('departure', 'Departure'), ('arrival', 'Arrival'), ('speed_change', 'Speed Change'), ('course_change', 'Course Change')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.vesselsubscription')),
            ],
            options={
                'db_table': 'core_vessel_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vesselsubscription',
            index=models.Index(fields=['user', 'is_active'], name='core_vessel_user_id_c036b0_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselsubscription',
            index=models.Index(fields=['vessel', 'is_active'], name='core_vessel_vessel__3e0bfb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vesselsubscription',
            unique_together={('user', 'vessel')},
        ),
        migrations.AddIndex(
            model_name='vesselalert',
            index=models.Index(fields=['subscription', '-created_at'], name='core_vessel_subscri_1088fc_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselalert',
            index=models.Index(fields=['status', '-created_at'], name='core_vessel_status_0e3b12_idx'),
        ),
    ]
