# Generated by Django 5.2.9 on 2025-12-20 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vessel_destination_vesselsubscription_vesselalert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], default='unread', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.event'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-timestamp'], name='core_notifi_user_id_d737be_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='core_notifi_status_7f445c_idx'),
        ),
    ]
