# Generated by Django 5.2.9 on 2025-12-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_status_alter_notification_event_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_status_7f445c_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
    ]
