# Generated by Django 5.2.9 on 2025-12-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_notification_core_notifi_status_7f445c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('position_update', 'Position Update'), ('arrival', 'Arrival'), ('departure', 'Departure'), ('unknown', 'Unknown')], db_column='event_type', default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_column='is_read', default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', '-timestamp'], name='core_notifi_is_read_576c18_idx'),
        ),
    ]
