# Generated by Django 5.2.9 on 2025-12-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_event_type_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Port latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Port longitude coordinate', null=True),
        ),
    ]
