# Generated by Django 5.2.9 on 2026-01-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_port_latitude_port_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='berthing_time',
            field=models.DateTimeField(blank=True, help_text='When vessel docks at the destination port', null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='entry_time',
            field=models.DateTimeField(blank=True, help_text='When vessel enters the destination port', null=True),
        ),
    ]
