# Generated by Django 5.2.9 on 2026-01-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_voyage_berthing_time_voyage_entry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiracyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('incidents_90_days', models.IntegerField(default=0)),
                ('last_incident_date', models.DateField(blank=True, null=True)),
                ('radius_km', models.FloatField(default=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_piracy_zone',
            },
        ),
    ]
