# Generated by Django 5.2.9 on 2026-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piracyzone',
            options={'ordering': ['-risk_level', '-incidents_90_days']},
        ),
        migrations.AddField(
            model_name='piracyzone',
            name='accident_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='piracyzone',
            name='accident_types',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='piracyzone',
            name='casualties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piracyzone',
            name='last_accident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piracyzone',
            name='total_accidents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piracyzone',
            name='vessels_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='piracyzone',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='piracyzone',
            name='radius_km',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='piracyzone',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='piracyzone',
            table=None,
        ),
    ]
