# Generated by Django 5.2.9 on 2026-01-05 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_piracyzone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Alert name (e.g., Hurricane Zone - Atlantic)', max_length=200)),
                ('latitude', models.FloatField(help_text='Center latitude of weather alert')),
                ('longitude', models.FloatField(help_text='Center longitude of weather alert')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('extreme', 'Extreme')], default='moderate', max_length=50)),
                ('weather_type', models.CharField(choices=[('hurricane', 'Hurricane'), ('tropical_storm', 'Tropical Storm'), ('typhoon', 'Typhoon'), ('cyclone', 'Cyclone'), ('thunderstorm', 'Severe Thunderstorm'), ('fog', 'Dense Fog'), ('high_winds', 'High Winds'), ('rough_seas', 'Rough Seas'), ('ice', 'Ice Hazard')], max_length=50)),
                ('radius_km', models.IntegerField(default=150, help_text='Alert radius in kilometers')),
                ('description', models.TextField(blank=True, help_text='Detailed weather description')),
                ('alert_issued', models.DateTimeField(default=django.utils.timezone.now, help_text='When alert was issued')),
                ('alert_expires', models.DateTimeField(blank=True, help_text='When alert expires', null=True)),
                ('wind_speed_kmh', models.IntegerField(blank=True, help_text='Wind speed in km/h', null=True)),
                ('wave_height_m', models.FloatField(blank=True, help_text='Wave height in meters', null=True)),
                ('visibility_km', models.FloatField(blank=True, help_text='Visibility in kilometers', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is alert currently active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_weather_alert',
                'ordering': ['-severity', '-alert_issued'],
            },
        ),
    ]
