# Generated by Django 5.2.9 on 2026-01-16 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_weatheralert'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('profile_view', 'Profile View'), ('profile_edit', 'Profile Edit'), ('profile_delete', 'Profile Delete'), ('vessel_create', 'Vessel Create'), ('vessel_view', 'Vessel View'), ('vessel_edit', 'Vessel Edit'), ('vessel_delete', 'Vessel Delete'), ('vessel_list', 'Vessel List'), ('voyage_create', 'Voyage Create'), ('voyage_view', 'Voyage View'), ('voyage_edit', 'Voyage Edit'), ('voyage_delete', 'Voyage Delete'), ('voyage_list', 'Voyage List'), ('port_view', 'Port View'), ('port_edit', 'Port Edit'), ('port_list', 'Port List'), ('notification_view', 'Notification View'), ('notification_mark_read', 'Notification Mark Read'), ('notification_delete', 'Notification Delete'), ('notification_list', 'Notification List'), ('subscription_create', 'Subscription Create'), ('subscription_delete', 'Subscription Delete'), ('subscription_list', 'Subscription List'), ('alert_view', 'Alert View'), ('alert_dismiss', 'Alert Dismiss'), ('alert_list', 'Alert List'), ('dashboard_view', 'Dashboard View'), ('dashboard_export', 'Dashboard Export'), ('admin_user_list', 'Admin User List'), ('admin_user_edit', 'Admin User Edit'), ('admin_user_delete', 'Admin User Delete'), ('admin_logs_view', 'Admin Logs View'), ('admin_system_info', 'Admin System Info'), ('unknown', 'Unknown')], db_index=True, max_length=50)),
                ('status_code', models.IntegerField(choices=[(200, '200 OK'), (201, '201 Created'), (204, '204 No Content'), (400, '400 Bad Request'), (401, '401 Unauthorized'), (403, '403 Forbidden'), (404, '404 Not Found'), (409, '409 Conflict'), (500, '500 Server Error'), (503, '503 Service Unavailable')])),
                ('endpoint', models.CharField(help_text='API endpoint or view name', max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information', null=True)),
                ('request_data', models.JSONField(blank=True, help_text='Request parameters (sanitized)', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response data (sanitized)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='e.g., Vessel, Voyage, Port', max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Action',
                'verbose_name_plural': 'User Actions',
                'db_table': 'core_user_action',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_user_a_user_id_654788_idx'), models.Index(fields=['action', '-timestamp'], name='core_user_a_action_1066f6_idx'), models.Index(fields=['status_code', '-timestamp'], name='core_user_a_status__6c2ef6_idx'), models.Index(fields=['-timestamp'], name='core_user_a_timesta_a2f8db_idx')],
            },
        ),
    ]
