# Generated by Django 4.2.7 on 2025-12-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0001_initial'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('cargo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_voyages', to='ports.port')),
                ('origin_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_voyages', to='ports.port')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='VoyageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('departure', 'Departure'), ('arrival', 'Arrival'), ('port_call', 'Port Call'), ('delay', 'Delay'), ('weather', 'Weather Event'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='voyages.voyage')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
