# Generated by Django 5.0.14 on 2026-01-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('arrivals', models.IntegerField(default=0)),
                ('departures', models.IntegerField(default=0)),
                ('avg_wait_time', models.FloatField(default=0.0)),
                ('congestion_score', models.FloatField(default=0.0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
