# Generated by Django 5.0.14 on 2026-01-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='arrivals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='port',
            name='departures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
