# Generated by Django 6.0 on 2025-12-17 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('vessel_type', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=255)),
                ('eta', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('course', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='tracking.vessel')),
            ],
        ),
    ]
