# Generated by Django 6.0 on 2025-12-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
