# Generated by Django 4.2.7 on 2025-12-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vessels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_vessels", models.PositiveIntegerField(default=0)),
                ("active_voyages", models.PositiveIntegerField(default=0)),
                ("completed_voyages", models.PositiveIntegerField(default=0)),
                ("active_alerts", models.PositiveIntegerField(default=0)),
                ("port_congestion_avg", models.FloatField(default=0.0)),
                ("efficiency_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PortPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("arrivals", models.PositiveIntegerField(default=0)),
                ("departures", models.PositiveIntegerField(default=0)),
                (
                    "average_turnaround_time",
                    models.FloatField(help_text="Average turnaround time in hours"),
                ),
                (
                    "peak_congestion_level",
                    models.CharField(default="low", max_length=20),
                ),
                ("throughput_tons", models.FloatField(default=0.0)),
                (
                    "efficiency_rating",
                    models.FloatField(default=0.0, help_text="Efficiency rating 0-100"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("weather", "Weather Risk"),
                            ("piracy", "Piracy Risk"),
                            ("mechanical", "Mechanical Risk"),
                            ("route", "Route Risk"),
                            ("cargo", "Cargo Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("risk_score", models.FloatField(help_text="Risk score 0-100")),
                ("description", models.TextField()),
                ("mitigation_measures", models.TextField(blank=True)),
                ("assessment_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="VoyageAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_duration",
                    models.FloatField(help_text="Planned duration in hours"),
                ),
                (
                    "actual_duration",
                    models.FloatField(
                        blank=True, help_text="Actual duration in hours", null=True
                    ),
                ),
                ("delay_hours", models.FloatField(default=0.0)),
                (
                    "fuel_consumption",
                    models.FloatField(
                        blank=True, help_text="Fuel consumption in tons", null=True
                    ),
                ),
                (
                    "average_speed",
                    models.FloatField(
                        blank=True, help_text="Average speed in knots", null=True
                    ),
                ),
                (
                    "weather_delays",
                    models.FloatField(
                        default=0.0, help_text="Weather-related delays in hours"
                    ),
                ),
                (
                    "port_delays",
                    models.FloatField(
                        default=0.0, help_text="Port-related delays in hours"
                    ),
                ),
                (
                    "efficiency_score",
                    models.FloatField(
                        default=0.0, help_text="Overall efficiency score 0-100"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "voyage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="vessels.voyage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
