# Generated by Django 4.2.7 on 2025-12-25 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='ports.port')),
                ('origin_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='ports.port')),
            ],
        ),
        migrations.CreateModel(
            name='VoyageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('departure', 'Departure'), ('arrival', 'Arrival'), ('port_call', 'Port Call'), ('anchor', 'Anchoring'), ('emergency', 'Emergency'), ('maintenance', 'Maintenance')], max_length=20)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.voyage')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
