# Generated by Django 4.2.7 on 2025-12-24 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vessels", "0001_initial"),
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessment",
            name="assessed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="vessel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_assessments",
                to="vessels.vessel",
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="voyage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vessels.voyage",
            ),
        ),
        migrations.AddField(
            model_name="portperformance",
            name="port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_metrics",
                to="ports.port",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dashboardmetrics",
            unique_together={("date",)},
        ),
        migrations.AlterUniqueTogether(
            name="portperformance",
            unique_together={("port", "date")},
        ),
    ]
