# Generated by Django 4.2.7 on 2025-12-25 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vessels', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='vessels.vessel'),
        ),
    ]
