# Generated by Django 4.2.7 on 2026-01-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("voyage_history", "0001_initial"),
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskassessment",
            name="voyage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="voyage_history.voyagereplay",
            ),
        ),
        migrations.AlterField(
            model_name="voyageanalytics",
            name="voyage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="voyage_history.voyagereplay",
            ),
        ),
    ]
