# Generated by Django 5.0.14 on 2025-12-15 12:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='City or geographical location', max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('congestion_score', models.FloatField(default=0.0, help_text='Congestion score (0-100, higher means more congested)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_wait_time', models.FloatField(default=0.0, help_text='Average wait time in hours')),
                ('arrivals', models.IntegerField(default=0, help_text='Number of vessel arrivals (current period)')),
                ('departures', models.IntegerField(default=0, help_text='Number of vessel departures (current period)')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Last update timestamp for analytics')),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Ports',
                'db_table': 'ports',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country'], name='ports_country_c3d661_idx'), models.Index(fields=['-congestion_score'], name='ports_congest_b2a526_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo_number', models.CharField(help_text='International Maritime Organization number (unique identifier)', max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('cargo', 'Cargo Ship'), ('tanker', 'Tanker'), ('passenger', 'Passenger Ship'), ('fishing', 'Fishing Vessel'), ('military', 'Military Vessel'), ('other', 'Other')], max_length=50)),
                ('flag', models.CharField(help_text='Flag country of the vessel', max_length=100)),
                ('cargo_type', models.CharField(blank=True, help_text='Type of cargo being transported', max_length=100, null=True)),
                ('operator', models.CharField(blank=True, help_text='Vessel operator/company name', max_length=200, null=True)),
                ('last_position_lat', models.FloatField(blank=True, help_text='Last known latitude', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('last_position_lon', models.FloatField(blank=True, help_text='Last known longitude', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Timestamp of last position update')),
            ],
            options={
                'verbose_name': 'Vessel',
                'verbose_name_plural': 'Vessels',
                'db_table': 'vessels',
                'ordering': ['-last_update'],
                'indexes': [models.Index(fields=['imo_number'], name='vessels_imo_num_aef299_idx'), models.Index(fields=['type'], name='vessels_type_52cdef_idx'), models.Index(fields=['-last_update'], name='vessels_last_up_e118f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('weather', 'Weather Alert'), ('piracy', 'Piracy Risk'), ('accident', 'Accident'), ('congestion', 'Port Congestion'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(help_text='Location description or coordinates', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(help_text='Detailed description of the event')),
                ('vessel', models.ForeignKey(help_text='Related vessel (if applicable)', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.vessel')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(blank=True, help_text='Actual or scheduled departure time', null=True)),
                ('arrival_time', models.DateTimeField(blank=True, help_text='Actual or estimated arrival time', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('port_from', models.ForeignKey(help_text='Origin port', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures_from', to='accounts.port')),
                ('port_to', models.ForeignKey(help_text='Destination port', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals_to', to='accounts.port')),
                ('vessel', models.ForeignKey(help_text='Vessel making this voyage', on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='accounts.vessel')),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
                'db_table': 'voyages',
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Notification message')),
                ('type', models.CharField(choices=[('alert', 'Alert'), ('warning', 'Warning'), ('info', 'Information')], default='info', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read this notification')),
                ('event', models.ForeignKey(blank=True, help_text='Related event (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.event')),
                ('user', models.ForeignKey(help_text='User receiving this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(blank=True, help_text='Related vessel (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.vessel')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='notificatio_user_id_5d4812_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='events_event_t_c9f56c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-timestamp'], name='events_timesta_e69029_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['vessel', '-departure_time'], name='voyages_vessel__b33ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['status'], name='voyages_status_e737ff_idx'),
        ),
    ]
