# Generated by Django 4.2.7 on 2025-12-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="port",
            name="timezone",
        ),
        migrations.RemoveField(
            model_name="portcongestion",
            name="congestion_level",
        ),
        migrations.AddField(
            model_name="port",
            name="annual_throughput",
            field=models.PositiveIntegerField(default=0, help_text="TEU per year"),
        ),
        migrations.AddField(
            model_name="port",
            name="berths",
            field=models.PositiveIntegerField(default=10, help_text="Number of berths"),
        ),
        migrations.AddField(
            model_name="port",
            name="port_efficiency_index",
            field=models.FloatField(default=1.0, help_text="UNCTAD efficiency index"),
        ),
        migrations.AddField(
            model_name="portcongestion",
            name="arrivals_24h",
            field=models.PositiveIntegerField(
                default=0, help_text="Arrivals in last 24h"
            ),
        ),
        migrations.AddField(
            model_name="portcongestion",
            name="departures_24h",
            field=models.PositiveIntegerField(
                default=0, help_text="Departures in last 24h"
            ),
        ),
        migrations.AddField(
            model_name="portcongestion",
            name="throughput_efficiency",
            field=models.FloatField(
                default=1.0, help_text="Current vs expected throughput"
            ),
        ),
        migrations.CreateModel(
            name="VesselMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vessel_name", models.CharField(max_length=200)),
                ("vessel_imo", models.CharField(blank=True, max_length=20)),
                ("vessel_mmsi", models.CharField(blank=True, max_length=20)),
                ("vessel_type", models.CharField(default="cargo", max_length=50)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("arrival", "Arrival"), ("departure", "Departure")],
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                ("actual_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("arrived", "Arrived"),
                            ("berthed", "Berthed"),
                            ("departed", "Departed"),
                            ("delayed", "Delayed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("wait_time_hours", models.FloatField(default=0)),
                ("cargo_volume", models.FloatField(default=0, help_text="TEU or tons")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vessel_movements",
                        to="ports.port",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_time"],
            },
        ),
    ]
