# Generated by Django 6.0 on 2025-12-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('port_type', models.CharField(blank=True, max_length=100)),
                ('berths', models.IntegerField(default=0)),
            ],
        ),
    ]
