# Generated by Django 6.0 on 2026-01-05 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imo_number', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('flag', models.CharField(blank=True, max_length=50)),
                ('cargo_type', models.CharField(blank=True, max_length=100, null=True)),
                ('last_position_lat', models.FloatField(null=True)),
                ('last_position_lon', models.FloatField(null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='port',
            name='berths',
        ),
        migrations.RemoveField(
            model_name='port',
            name='port_type',
        ),
        migrations.AddField(
            model_name='port',
            name='avg_wait_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='port',
            name='congestion_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='port',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='VoyageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='coreapi.vessel')),
            ],
        ),
    ]
