# Generated by Django 5.2.8 on 2026-01-13 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vessel_latitude_vessel_longitude_vessel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.FloatField()),
                ('heading', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('violation_status', models.CharField(default='Normal', max_length=50)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_from', models.CharField(max_length=100)),
                ('port_to', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Transit', 'In Transit'), ('Arrived', 'Arrived'), ('Delayed', 'Delayed')], default='Scheduled', max_length=20)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='api.vessel')),
            ],
        ),
    ]
